"""Build `data/attention.json`: the needs-attention queue the page shows and Zeus works.

Every open PR gets the states that apply to it (conflicting, failing checks, a reply
or change request owed, unknown merge state, ready but quiet, AI note), the single most
urgent one as `state`, and an `actionable` flag that is true only when something changed
since the autoresolver or Zeus last acted on it. That memory comes from the hidden
`<!-- hermes-autotriage -->` sentinel the bots put on every comment they post.

Inputs, both committed in this repo:
  config/queue.json   reviewer trust tiers, expected check failures, nudge switch, open-PR cap
  config/parked.json  PRs set aside on purpose, each with conditions that wake it up

Stdlib only. `build()` takes the refresh script's cached `gh()` so threads the battle-log
pass already read are not fetched twice.
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timedelta, timezone
from typing import Callable

SCHEMA_VERSION = 1
SENTINEL = "<!-- hermes-autotriage -->"
ACTION_RE = re.compile(r"<!--[^>]*?\baction=([\w-]+)[^>]*?-->")
HEAD_RE = re.compile(r"<!--[^>]*?\bhead=([0-9a-f]{7,40})[^>]*?-->")
AI_NOTE_RE = re.compile(r"^\s*(?:AI code review|\*?This was generated by AI)|generated by AI during triage", re.I)
MENTION_RE = re.compile(r"(?<![\w`])@([A-Za-z0-9][\w-]*)")
FAILED = {"failure", "timed_out", "action_required", "startup_failure"}
AGGREGATE_CHECK = "All required checks pass"

# state → (priority, suggestedAction). Lower priority is more urgent.
STATES = {
    "changes_requested": (0, "address_review"),
    "conflicting":       (0, "rebase"),
    "checks_failing":    (1, "fix_checks"),
    "reply_owed":        (1, "reply"),
    "merge_unknown":     (2, "recheck_merge"),
    "ready_stale":       (3, "nudge"),
    "fyi":               (4, "none"),
    "ai_note":           (4, "none"),
}
# Bot actions after which an unchanged PR in this state still needs another pass
# (upstream main keeps moving under a conflicting branch even when nobody comments).
RETRY_UNCHANGED = {"conflicting": {"rebased", "salvaged-pr", "recheck_merge"}}
DEFAULT_CONFIG = {
    "reviewers": {"maintainer": [], "substantive": [], "noise": [], "default": "substantive"},
    "expectedFailures": [],
    "nudge": {"enabled": False, "afterDays": 14, "everyDays": 30},
    "openCap": 73,
}


def _ts(s: str | None) -> datetime | None:
    return datetime.fromisoformat(s.replace("Z", "+00:00")) if s else None


def _iso(d: datetime) -> str:
    return d.strftime("%Y-%m-%dT%H:%M:%SZ")


def _excerpt(body: str, limit: int = 200) -> str:
    text = re.sub(r"<!--.*?-->", " ", body or "", flags=re.S)
    text = re.sub(r"```.*?```", " [code] ", text, flags=re.S)
    text = re.sub(r"[*`>#|]+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1].rsplit(" ", 1)[0] + "…"


def load_config(config_dir: str) -> tuple[dict, list[dict]]:
    cfg = json.loads(json.dumps(DEFAULT_CONFIG))
    try:
        with open(os.path.join(config_dir, "queue.json"), encoding="utf-8") as fh:
            user = json.load(fh)
        for k, v in user.items():
            cfg[k] = {**cfg[k], **v} if isinstance(cfg.get(k), dict) and isinstance(v, dict) else v
    except (OSError, ValueError):
        pass
    try:
        with open(os.path.join(config_dir, "parked.json"), encoding="utf-8") as fh:
            parked = json.load(fh).get("parked", [])
    except (OSError, ValueError):
        parked = []
    return cfg, parked


def trust_of(login: str, body: str, cfg: dict) -> str:
    if AI_NOTE_RE.search(body or ""):
        return "noise"
    tiers = cfg["reviewers"]
    for tier in ("maintainer", "substantive", "noise"):
        if login.lower() in {x.lower() for x in tiers.get(tier, [])}:
            return tier
    return tiers.get("default", "substantive")


def thread(gh: Callable, repo: str, n: int, author: str, is_bot: Callable[[str], bool]) -> list[dict]:
    """Issue comments and reviews on a PR as one oldest-first list of events."""
    events = []
    for c in gh(f"repos/{repo}/issues/{n}/comments", per_page=100) or []:
        who = c["user"]["login"]
        if is_bot(who) or not (c.get("body") or "").strip():
            continue
        events.append({"who": who, "at": c["created_at"], "kind": "comment", "body": c["body"],
                       "url": c.get("html_url"), "self": who == author})
    for r in gh(f"repos/{repo}/pulls/{n}/reviews", per_page=100) or []:
        who, at, state = r["user"]["login"], r.get("submitted_at"), r.get("state")
        if is_bot(who) or not at or state == "PENDING":
            continue
        body = r.get("body") or ""
        if state == "COMMENTED" and not body.strip():
            body = "(inline review comments)"
        events.append({"who": who, "at": at, "kind": "changes" if state == "CHANGES_REQUESTED" else
                       "approve" if state == "APPROVED" else "review", "body": body,
                       "url": r.get("html_url"), "self": who == author})
    return sorted(events, key=lambda e: e["at"])


def last_bot_action(events: list[dict]) -> dict | None:
    for e in reversed(events):
        if e["self"] and SENTINEL in e["body"]:
            action = ACTION_RE.search(e["body"])
            head = HEAD_RE.search(e["body"])
            return {"action": action.group(1) if action else "commented",
                    "sha": head.group(1)[:7] if head else None, "at": e["at"], "commentUrl": e["url"]}
    return None


def check_failures(gh: Callable, repo: str, sha: str, expected: list[str]) -> tuple[list[str], bool]:
    """(unexpected failing check names, whether any checks ran at all) for a head commit."""
    data = gh(f"repos/{repo}/commits/{sha}/check-runs", per_page=100) or {}
    runs = data.get("check_runs") or []
    patterns = [re.compile(p, re.I) for p in expected]
    failing = sorted({r["name"] for r in runs if r.get("conclusion") in FAILED
                      and r["name"] != AGGREGATE_CHECK and not any(p.search(r["name"]) for p in patterns)})
    return failing, bool(runs)


def head_commit_at(gh: Callable, repo: str, n: int) -> str | None:
    commits = gh(f"repos/{repo}/pulls/{n}/commits", per_page=100) or []
    return ((commits[-1].get("commit") or {}).get("committer") or {}).get("date") if commits else None


def wake_reason(gh: Callable, repo: str, entry: dict, last_human: dict | None, now: datetime) -> str | None:
    """Which of a parked PR's wake conditions fired, if any."""
    wake, parked_at = entry.get("wake") or {}, entry.get("parkedAt") or ""
    if wake.get("after") and now >= _ts(wake["after"]):
        return f"date {wake['after'][:10]} reached"
    if wake.get("onNewHumanComment", True) and last_human and last_human["at"] > parked_at:
        return f"new comment from {last_human['who']}"
    for path in wake.get("paths") or []:
        hits = gh(f"repos/{repo}/commits", path=path, since=parked_at, per_page=1) or []
        if hits:
            return f"upstream main touched {path} ({hits[0]['sha'][:10]})"
    return None


def build(gh: Callable, repo: str, author: str, prs: list[dict], pulls: dict[int, dict],
          is_bot: Callable[[str], bool], config_dir: str, generated_at: str) -> dict:
    cfg, parked_cfg = load_config(config_dir)
    parked_by_pr = {e["pr"]: e for e in parked_cfg if isinstance(e, dict) and e.get("pr")}
    now = datetime.now(timezone.utc)
    main = gh(f"repos/{repo}/commits/main") or {}
    items, parked, needs_human = [], [], []
    open_prs = [p for p in prs if p["state"] == "open"]
    waiting = 0

    for p in open_prs:
        n = p["n"]
        pull = pulls.get(n) or {}
        if p.get("merge") == "draft":
            continue
        head = (pull.get("head") or {}).get("sha") or ""
        events = thread(gh, repo, n, author, is_bot)
        bot = last_bot_action(events)
        humans = [e for e in events if not e["self"]]
        last_human = humans[-1] if humans else None
        last_real = next((e for e in reversed(humans) if trust_of(e["who"], e["body"], cfg) != "noise"), None)
        self_at = max([e["at"] for e in events if e["self"]] + [head_commit_at(gh, repo, n) or ""])

        reasons = []
        merge = p.get("merge") or "unknown"
        if merge == "dirty":
            reasons.append({"kind": "conflicting", "detail": "Conflicts with main; rebase it."})
        failing, ran = check_failures(gh, repo, head, cfg["expectedFailures"]) if head else ([], False)
        if failing:
            reasons.append({"kind": "checks_failing", "detail": "Failing: " + ", ".join(failing[:6]),
                            "checks": failing})
        for e in reversed(humans):  # each reviewer's newest verdict counts once
            if e["kind"] == "changes" and e["at"] > self_at and \
                    not any(x["who"] == e["who"] and x["at"] > e["at"] and x["kind"] == "approve" for x in humans):
                reasons.append({"kind": "changes_requested", "who": e["who"], "at": e["at"],
                                "trust": trust_of(e["who"], e["body"], cfg), "excerpt": _excerpt(e["body"]),
                                "url": e["url"]})
                break
        if last_human and last_human["at"] > self_at and last_human["kind"] != "approve" \
                and not any(r["kind"] == "changes_requested" for r in reasons):
            trust = trust_of(last_human["who"], last_human["body"], cfg)
            # Pinging someone else (often a maintainer, "please review") is not a reply owed by the author.
            prose = re.sub(r"```.*?```|`[^`]*`|<!--.*?-->", " ", last_human["body"], flags=re.S)
            mentions = {m.lower() for m in MENTION_RE.findall(prose)}
            aside = bool(mentions) and author.lower() not in mentions
            kind = "ai_note" if trust == "noise" else "fyi" if aside else "reply_owed"
            reasons.append({"kind": kind, "who": last_human["who"],
                            "trust": trust, "at": last_human["at"], "excerpt": _excerpt(last_human["body"]),
                            "url": last_human["url"]})
        if merge == "unknown":
            reasons.append({"kind": "merge_unknown", "detail": "GitHub has not computed mergeability yet."})
        quiet_days = (now - _ts(p["updated"])).days
        if merge == "clean" and quiet_days >= cfg["nudge"]["afterDays"]:
            reasons.append({"kind": "ready_stale", "detail": f"Mergeable and quiet for {quiet_days} days."})

        entry, woke = parked_by_pr.get(n), None
        if entry:
            woke = wake_reason(gh, repo, entry, last_real, now)
            if not woke:
                parked.append({**entry, "wokenBy": None, "state": reasons and min(
                    reasons, key=lambda r: STATES[r["kind"]][0])["kind"] or None})
                continue
        if not reasons:
            waiting += 1
            continue
        reasons.sort(key=lambda r: STATES[r["kind"]][0])
        state = reasons[0]["kind"]
        priority, action = STATES[state]

        escalated = bool(bot and bot["action"] == "escalated" and
                         not any(e["self"] and SENTINEL not in e["body"] and e["at"] > bot["at"] for e in events))
        changed = (bot is None
                   or (bot["sha"] and not head.startswith(bot["sha"]))
                   or bool(last_real and last_real["at"] > bot["at"])
                   or bot["action"] in RETRY_UNCHANGED.get(state, ()))
        if state == "ready_stale":
            recent_nudge = any(e["self"] and "action=nudged" in e["body"] and
                               now - _ts(e["at"]) < timedelta(days=cfg["nudge"]["everyDays"]) for e in events)
            changed = cfg["nudge"]["enabled"] and not recent_nudge

        item = {
            "pr": n, "title": p["title"], "url": f"https://github.com/{repo}/pull/{n}", "issue": p.get("issue"),
            "headSha": head[:7] or None, "updated": p["updated"], "ageDays": (now - _ts(p["created"])).days,
            "state": state, "priority": priority, "suggestedAction": action,
            "actionable": bool(changed) and not escalated and STATES[state][1] != "none",
            "needsHuman": escalated, "reasons": reasons,
            "evidence": {"merge": merge, "failingChecks": failing, "checksRan": ran},
            "lastBotAction": bot,
        }

        if woke:
            item["wokenBy"] = woke
        if escalated:
            needs_human.append({"pr": n, "title": p["title"], "url": item["url"], "since": bot["at"],
                                "commentUrl": bot["commentUrl"]})
        items.append(item)

    items.sort(key=lambda i: (i["priority"], not i["actionable"], i["updated"]))
    open_count = len(open_prs)
    return {
        "schemaVersion": SCHEMA_VERSION,
        "generatedAt": _iso(now),
        "snapshotGeneratedAt": generated_at,
        "repo": repo, "author": author,
        "upstreamMainSha": main.get("sha"),
        "capacity": {"open": open_count, "cap": cfg["openCap"], "free": max(0, cfg["openCap"] - open_count)},
        "counts": {"actionable": sum(i["actionable"] for i in items), "listed": len(items),
                   "waiting": waiting, "parked": len(parked), "needsHuman": len(needs_human)},
        "items": items, "parked": parked, "needsHuman": needs_human,
    }
