#!/usr/bin/env python3
"""Build the Hermes Base dashboard snapshot from GitHub.

Collects every PR the autoresolver opened on the upstream repo, classifies
closed-but-unmerged PRs (salvaged / superseded / duplicate) from their
comments, and assembles a battle-log feed of recent reviews, comments,
pushes, merges and closures.

Requires an authenticated GitHub CLI (`gh auth status`). Stdlib only.

    python3 refresh_snapshot.py --out snapshot.json

The output is the snapshot the page fetches (`data/snapshot.json`), plus one
battle-log file per whole day in the window (`data/feed/<YYYY-MM-DD>.json`) so history
survives after it leaves the --days window. `data/feed/index.json` lists every feed file
for the page to load.

Closures already classified in the dashboard's seed snapshot (verified by hand
against comments and upstream git history) keep that classification; only new
closures are classified from comments. Every closed, unmerged PR is also checked
for silent cherry-picks: if one of its commits reached upstream `main` with the
same author timestamp or subject, it is marked salvaged whatever the comments say.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timedelta, timezone

import attention

# A maintainer saying this PR's own work reached main.
SALVAGE_RE = re.compile(r"salvaged? (?:in|into|as|via)|cherry-?pick|co-authored|authorship (?:is |was )?preserved|"
                        r"(?:landed|merged) (?:on main )?via (?:PR )?#|with (?:co-author )?credit|both your commits", re.I)
DUPLICATE_RE = re.compile(r"\bduplicate\b|opened (?:first|earlier|~?\d+ ?min)|(?:filed|opened)[^.]{0,30}earlier|"
                          r"the earlier\b", re.I)
SUPERSEDED_RE = re.compile(r"supersed|already (?:fixed|landed|implemented|on main|resolves)|fixed on main|redundant|"
                           r"in favou?r of|now (?:implements|fixes|handles|resolves)|implemented on main|resolved (?:at|by)", re.I)
WITHDRAWN_RE = re.compile(r"withdraw|can(?:'|no)t reproduce|non-reproducible|no-op|maintainer review (?:is|confirms)", re.I)
NOTPLANNED_RE = re.compile(r"per (?:standing )?policy|not planned|out of core|belongs? in (?:the )?provider", re.I)
NOISE_RE = re.compile(r"generated by AI during triage", re.I)
SEED_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed-snapshot.json")
LABEL_KINDS = (("sweeper:implemented-on-main", "superseded"), ("sweeper:not-planned", "notplanned"), ("duplicate", "duplicate"))
FOOTER_RE = re.compile(r"\n-{3,}\s*\n_?Generated by \[Claude Code\].*", re.S)
MAX_DOC_BYTES = 240_000
_CACHE: dict[tuple, object] = {}


def gh(path: str, _fresh: bool = False, **params) -> object:
    """GET a GitHub API path. Reads are cached for the run; `_fresh` skips the cache."""
    key = (path, tuple(sorted(params.items())))
    if not _fresh and key in _CACHE:
        return _CACHE[key]
    _CACHE[key] = _gh(path, **params)
    return _CACHE[key]


def _gh(path: str, **params) -> object:
    cmd = ["gh", "api", "-X", "GET", path]
    for k, v in params.items():
        cmd += ["-f", f"{k}={v}"]
    # Retry transient failures (timeouts, 5xx, secondary rate limits) so one blip doesn't sink the run.
    for attempt in range(4):
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode == 0:
            return json.loads(res.stdout or "null")
        if "HTTP 404" in res.stderr or "HTTP 422" in res.stderr:
            break
        time.sleep(2 ** attempt * 3)
    raise RuntimeError(f"gh api {path} failed: {res.stderr.strip()}")


def clean(body: str | None, limit: int = 240) -> str:
    text = FOOTER_RE.sub("", body or "")
    text = re.sub(r"```.*?```", " [code] ", text, flags=re.S)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.S)
    text = re.sub(r"(^|\s)(?:#{1,6}|>+)\s", " ", text)
    text = re.sub(r"[*`|]+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1].rsplit(" ", 1)[0] + "…"


def split_title(title: str) -> tuple[str, int | None]:
    m = re.search(r"\s*\(#(\d+)\)\s*$", title)
    return (title[: m.start()] if m else title), (int(m.group(1)) if m else None)


def fetch_prs(repo: str, author: str) -> list[dict]:
    items, page = [], 1
    while True:
        data = gh("search/issues", q=f"author:{author} repo:{repo} is:pr", per_page=100, page=page,
                  sort="created", order="desc")
        items += data["items"]
        if len(data["items"]) < 100 or len(items) >= data["total_count"]:
            return items
        page += 1


def is_bot(login: str) -> bool:
    return login.endswith("[bot]") or login in ("coderabbitai", "github-actions")


def classify_comment(body: str, by_author: bool) -> str | None:
    """Closure kind a single closing-time comment implies, or None."""
    if by_author:
        # The autoresolver's own closing note: it never salvages its own work.
        for kind, rx in (("duplicate", DUPLICATE_RE), ("withdrawn", WITHDRAWN_RE), ("superseded", SUPERSEDED_RE)):
            if rx.search(body):
                return kind
        return None
    for kind, rx in (("salvaged", SALVAGE_RE), ("notplanned", NOTPLANNED_RE), ("duplicate", DUPLICATE_RE),
                     ("superseded", SUPERSEDED_RE)):
        if rx.search(body):
            return kind
    return None


def classify(repo: str, author: str, pr: dict) -> tuple[str | None, str | None, str | None]:
    """Return (closeKind, note, who) for a closed, unmerged PR, newest closing comment first."""
    comments = [c for c in gh(f"repos/{repo}/issues/{pr['n']}/comments", per_page=100) or []
                if not is_bot(c["user"]["login"]) and not NOISE_RE.search(c.get("body") or "")]
    cutoff = (datetime.fromisoformat(pr["closed"].replace("Z", "+00:00")) - timedelta(days=3)).strftime("%Y-%m-%dT%H:%M:%SZ")
    near = [c for c in comments if c["created_at"] >= cutoff] or comments
    for c in reversed(near):
        body, who = c.get("body") or "", c["user"]["login"]
        kind = classify_comment(body, who == author)
        if kind:
            return kind, clean(body, 180), who
    return None, None, None


def norm_subject(message: str) -> str:
    first = (message or "").splitlines()[0] if message else ""
    return re.sub(r"\s*\(#\d+\)\s*$", "", first).strip().lower()


def main_commits_by(repo: str, author: str, since: str) -> list[dict]:
    """Upstream default-branch commits whose author is `author` (login or email), newest first."""
    out, page = [], 1
    while True:
        batch = gh(f"repos/{repo}/commits", author=author, since=since, per_page=100, page=page) or []
        if not isinstance(batch, list):
            return out
        out += [c for c in batch if isinstance(c, dict) and c.get("sha") and (c.get("commit") or {}).get("author")]
        if len(batch) < 100:
            return out
        page += 1


PICKED_FROM_RE = re.compile(r"cherry picked from commit ([0-9a-f]{7,40})")
PR_REF_RE = re.compile(r"#(\d+)")


def cherry_pick_index(commits: list[dict]) -> tuple[dict, dict, dict, dict]:
    """Upstream commits by author date, subject, referenced PR number, and `-x` origin sha."""
    by_date, by_subject, by_ref, by_origin = {}, {}, {}, {}
    for c in reversed(commits):  # oldest first, so the latest landing wins
        message = c["commit"].get("message") or ""
        by_date[c["commit"]["author"]["date"]] = c
        by_subject[norm_subject(message)] = c
        for n in PR_REF_RE.findall(message):
            by_ref[int(n)] = c
        for sha in PICKED_FROM_RE.findall(message):
            by_origin[sha] = c
    return by_date, by_subject, by_ref, by_origin


def find_cherry_pick(repo: str, author_ids: set[str], pr: dict, index: tuple[dict, dict, dict, dict]) -> dict | None:
    """The upstream commit that carries this PR's own work, if any.

    A commit you authored that names this PR number (a maintainer's "salvage #N") counts on
    its own. Otherwise only the PR's own commits are compared: authored by the autoresolver
    and dated no more than three hours before the PR opened, which skips commits a stacked
    branch inherited. They match by `cherry picked from` origin, author date or subject.
    """
    by_date, by_subject, by_ref, by_origin = index
    if pr["n"] in by_ref:
        return by_ref[pr["n"]]
    opened = datetime.fromisoformat(pr["created"].replace("Z", "+00:00")) - timedelta(hours=3)
    for c in gh(f"repos/{repo}/pulls/{pr['n']}/commits", per_page=100) or []:
        info = c.get("commit") or {}
        who = {((c.get("author") or {}).get("login") or "").lower(), (info.get("author", {}).get("email") or "").lower()}
        if not (who & author_ids):
            continue
        date = info.get("author", {}).get("date") or ""
        if not date or datetime.fromisoformat(date.replace("Z", "+00:00")) < opened:
            continue
        sha = c.get("sha") or ""
        hit = (next((v for k, v in by_origin.items() if sha.startswith(k) or k.startswith(sha)), None) if sha else None) \
            or by_date.get(date) or by_subject.get(norm_subject(info.get("message")))
        if hit:
            return hit
    return None


def salvage_from_commit(hit: dict) -> tuple[str, str]:
    login = (hit.get("committer") or {}).get("login") or ""
    via = login if login and login != "web-flow" else hit["commit"]["committer"]["name"]
    day = datetime.fromisoformat(hit["commit"]["committer"]["date"].replace("Z", "+00:00"))
    note = (f"Cherry-picked onto main by {via} on {day.strftime('%b')} {day.day} "
            f"({hit['sha'][:10]}), with you kept as the commit author.")
    return via, note


def load_prior(path: str | None) -> dict[int, dict]:
    """Hand-verified closure classifications, keyed by PR number."""
    try:
        with open(path or SEED_PATH) as fh:
            return {p["n"]: p for p in json.load(fh).get("prs", []) if p.get("closeKind")}
    except (OSError, ValueError):
        return {}


def feed_for(repo: str, author: str, pr: dict, since: str) -> list[dict]:
    n, ev = pr["n"], []
    if pr["created"] >= since:
        ev.append({"at": pr["created"], "who": author, "pr": n, "kind": "open",
                   "text": "Opened: " + pr["title"] + (f" (fixes #{pr['issue']})" if pr.get("issue") else "")})
    for c in gh(f"repos/{repo}/issues/{n}/comments", per_page=100) or []:
        if is_bot(c["user"]["login"]) or NOISE_RE.search(c.get("body") or ""):
            continue
        if c["created_at"] >= since and (c.get("body") or "").strip():
            ev.append({"at": c["created_at"], "who": c["user"]["login"], "pr": n, "kind": "comment",
                       "text": clean(c["body"])})
    for r in gh(f"repos/{repo}/pulls/{n}/reviews", per_page=100) or []:
        at = r.get("submitted_at") or ""
        if at < since:
            continue
        state = r.get("state")
        if state == "APPROVED":
            ev.append({"at": at, "who": r["user"]["login"], "pr": n, "kind": "approve",
                       "text": clean(r.get("body")) or "Approved."})
        elif state == "CHANGES_REQUESTED":
            ev.append({"at": at, "who": r["user"]["login"], "pr": n, "kind": "changes",
                       "text": clean(r.get("body")) or "Requested changes."})
        elif (r.get("body") or "").strip():
            ev.append({"at": at, "who": r["user"]["login"], "pr": n, "kind": "review", "text": clean(r["body"])})
    for c in gh(f"repos/{repo}/pulls/{n}/commits", per_page=100) or []:
        at = (c.get("commit") or {}).get("committer", {}).get("date") or ""
        initial = abs((datetime.fromisoformat(at.replace("Z", "+00:00")) -
                       datetime.fromisoformat(pr["created"].replace("Z", "+00:00"))).total_seconds()) < 3600 if at else True
        if at >= since and not initial:
            msg = (c["commit"].get("message") or "").splitlines()[0]
            ev.append({"at": at, "who": author, "pr": n, "kind": "push", "text": clean(msg, 160)})
    if pr["state"] == "merged" and (pr.get("closed") or "") >= since:
        full = gh(f"repos/{repo}/pulls/{n}")
        who = (full.get("merged_by") or {}).get("login") or "maintainer"
        pr["via"] = who
        ev.append({"at": pr["closed"], "who": who, "pr": n, "kind": "merge", "text": "Merged into main."})
    elif pr["state"] == "closed" and (pr.get("closed") or "") >= since:
        kind = "salvage" if pr.get("closeKind") == "salvaged" else "close"
        ev.append({"at": pr["closed"], "who": pr.get("via") or author, "pr": n, "kind": kind,
                   "text": pr.get("note") or "Closed without merging."})
    return ev


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default="NousResearch/hermes-agent")
    ap.add_argument("--author", default="PRATHAMESH75")
    ap.add_argument("--days", type=int, default=14, help="battle-log window in days")
    ap.add_argument("--feed-prs", type=int, default=100, help="most recently updated PRs to read threads from")
    ap.add_argument("--classify", type=int, default=200, help="recent closed PRs to classify from comments")
    ap.add_argument("--out", default="data/snapshot.json")
    ap.add_argument("--feed-dir", default="data/feed", help="where the per-day battle-log files and index.json live")
    ap.add_argument("--prior", help="snapshot whose closure classifications win (default: seed-snapshot.json next to this script)")
    ap.add_argument("--author-email", action="append", default=[],
                    help="extra commit email(s) the autoresolver commits as; the login is always checked")
    ap.add_argument("--no-cherry-picks", action="store_true", help="skip the upstream cherry-pick check")
    ap.add_argument("--attention-out", default="data/attention.json",
                    help="where the needs-attention queue goes; empty to skip it")
    ap.add_argument("--config-dir", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "config"),
                    help="holds queue.json (reviewer tiers, expected check failures) and parked.json")
    args = ap.parse_args()

    raw = fetch_prs(args.repo, args.author)
    prs, updated = [], {}
    for it in raw:
        title, issue = split_title(it["title"])
        merged_at = (it.get("pull_request") or {}).get("merged_at")
        state = "merged" if merged_at else it["state"]
        pr = {"n": it["number"], "title": title, "issue": issue, "state": state,
              "created": it["created_at"], "updated": it["updated_at"], "comments": it.get("comments", 0),
              "labels": [l["name"] for l in it.get("labels", [])]}
        if it.get("closed_at"):
            pr["closed"] = merged_at or it["closed_at"]
        prs.append(pr)
        updated[pr["n"]] = it["updated_at"]

    # Merge state for open PRs (dirty = conflicting, unstable = failing checks, blocked = awaiting
    # review). GitHub computes it lazily: the first read of a stale PR says "unknown" and starts
    # the computation, so those PRs are read once more after a short wait.
    pulls: dict[int, dict] = {}

    def read_merge(p: dict, fresh: bool = False) -> None:
        try:
            pull = gh(f"repos/{args.repo}/pulls/{p['n']}", _fresh=fresh)
            pulls[p["n"]] = pull
            p["merge"] = "draft" if pull.get("draft") else (pull.get("mergeable_state") or "unknown")
        except RuntimeError:
            p["merge"] = "unknown"

    for p in prs:
        if p["state"] == "open":
            read_merge(p)
    unknown = [p for p in prs if p.get("merge") == "unknown"]
    if unknown:
        time.sleep(8)
        for p in unknown:
            read_merge(p, fresh=True)

    prior = load_prior(args.prior)
    closed = [p for p in prs if p["state"] == "closed"]
    reused = 0
    for p in closed:
        known = prior.get(p["n"])
        if known:
            p.update({k: known[k] for k in ("closeKind", "note", "via") if known.get(k)})
            reused += 1
    # Git evidence first: a silent cherry-pick upgrades any non-salvaged closure, verified or not.
    picked = 0
    unsalvaged = [p for p in closed if p.get("closeKind") != "salvaged"]
    if unsalvaged and not args.no_cherry_picks:
        oldest = min(p["created"] for p in unsalvaged)
        since_pr = (datetime.fromisoformat(oldest.replace("Z", "+00:00")) - timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ")
        landed: dict[str, dict] = {}
        for ident in [args.author, *args.author_email]:
            for c in main_commits_by(args.repo, ident, since_pr):
                landed[c["sha"]] = c
        commits = sorted(landed.values(), key=lambda c: c["commit"]["committer"]["date"], reverse=True)
        author_ids = {i.lower() for i in [args.author, *args.author_email]}
        if commits:
            index = cherry_pick_index(commits)
            for p in unsalvaged:
                hit = find_cherry_pick(args.repo, author_ids, p, index)
                if hit:
                    p["closeKind"] = "salvaged"
                    p["via"], p["note"] = salvage_from_commit(hit)
                    picked += 1

    for p in [p for p in closed if not p.get("closeKind")][: args.classify]:
        kind, note, who = classify(args.repo, args.author, p)
        if kind:
            p["closeKind"], p["note"], p["via"] = kind, note, who
            continue
        for label, lk in LABEL_KINDS:
            if label in p["labels"]:
                p["closeKind"], p["note"] = lk, f"Labelled {label} on GitHub."
                break

    since = (datetime.now(timezone.utc) - timedelta(days=args.days)).strftime("%Y-%m-%dT%H:%M:%SZ")
    recent = sorted((p for p in prs if updated[p["n"]] >= since), key=lambda p: updated[p["n"]], reverse=True)
    feed = []
    for p in recent[: args.feed_prs]:
        feed += feed_for(args.repo, args.author, p, since)
    feed.sort(key=lambda e: e["at"], reverse=True)

    snap = {
        "repo": args.repo, "author": args.author,
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": "GitHub API via gh", "complete": True, "feedPrecision": "exact",
        "totals": {"all": len(prs), "open": sum(p["state"] == "open" for p in prs),
                   "merged": sum(p["state"] == "merged" for p in prs),
                   "closed": sum(p["state"] == "closed" for p in prs)},
        "prs": prs, "feed": feed[:120],
    }
    while len(json.dumps(snap)) > MAX_DOC_BYTES and snap["feed"]:
        snap["feed"] = snap["feed"][: len(snap["feed"]) * 3 // 4]
    with open(args.out, "w") as fh:
        json.dump(snap, fh)

    # One file per whole day in the window; the partial first day is skipped so a
    # shorter read never overwrites a fuller one stored by an earlier run.
    os.makedirs(args.feed_dir, exist_ok=True)
    by_day: dict[str, list] = {}
    for e in feed:
        if e["at"][:10] > since[:10]:
            by_day.setdefault(e["at"][:10], []).append(e)
    for day, events in sorted(by_day.items()):
        with open(os.path.join(args.feed_dir, f"{day}.json"), "w") as fh:
            json.dump({"day": day, "events": sorted(events, key=lambda e: e["at"])}, fh)
    docs = sorted(f for f in os.listdir(args.feed_dir) if f.endswith(".json") and f != "index.json")
    with open(os.path.join(args.feed_dir, "index.json"), "w") as fh:
        json.dump(docs, fh)

    queue = None
    if args.attention_out:
        # A failed queue build keeps the last committed attention.json rather than sinking the snapshot.
        try:
            queue = attention.build(gh, args.repo, args.author, prs, pulls, is_bot, args.config_dir,
                                    snap["generatedAt"])
            with open(args.attention_out, "w", encoding="utf-8") as fh:
                json.dump(queue, fh, indent=1)
        except Exception as exc:  # noqa: BLE001 — the snapshot above is already written
            print(f"attention queue not rebuilt: {exc}", file=sys.stderr)

    t = snap["totals"]
    print(f"wrote {args.out}: {t['all']} PRs ({t['open']} open, {t['merged']} merged, {t['closed']} closed), "
          f"{sum(1 for p in prs if p.get('closeKind'))} closures classified ({reused} from the verified seed, "
          f"{picked} silent cherry-picks found), "
          f"{len(snap['feed'])} feed events, {len(by_day)} daily feed files, "
          f"{sum(p.get('merge') == 'unknown' for p in prs)} merge states still unknown")
    if queue:
        c = queue["counts"]
        print(f"wrote {args.attention_out}: {c['listed']} listed ({c['actionable']} actionable), "
              f"{c['waiting']} waiting, {c['parked']} parked, {c['needsHuman']} need a human")
    return 0


if __name__ == "__main__":
    sys.exit(main())
